version: "3.9"

services:
  app:
    image: ghcr.io/bphndigitalservice/fungsionalpro:latest
    container_name: fungsionalpro
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
