#!/usr/bin/env sh

container_mode=${CONTAINER_MODE:-"http"}

if [ "${container_mode}" = "http" ]; then
    curl -sf http://localhost:8000 > /dev/null 2>&1
    exit $?
elif [ "${container_mode}" = "horizon" ]; then
    php artisan horizon:status --no-ansi > /dev/null 2>&1
    exit $?
elif [ "${container_mode}" = "scheduler" ]; then
    supervisorctl status scheduler:scheduler_00 > /dev/null 2>&1
    exit $?
elif [ "${container_mode}" = "worker" ]; then
    supervisorctl status worker:worker_00 > /dev/null 2>&1
    exit $?
else
    echo "Container mode mismatched."
    exit 1
fi